from __future__ import annotations

import hashlib
import json
import random
from pathlib import Path

OUT = Path("training/datasets/product_agent/generated_instructions/instructions_v2_family_authored.jsonl")
TARGET_PER_FAMILY = 500
SEED = 43

FAMILIES = {
    "authentication": {
        "artifacts": ["login attempts", "password reset requests", "MFA challenges", "user sessions", "device trust prompts", "account recovery requests"],
        "tasks": [
            "Limit repeated {artifact}.",
            "Prevent duplicate {artifact}.",
            "Improve failure handling for {artifact}.",
            "Require clearer user feedback when {artifact} fail.",
            "Detect suspicious patterns in {artifact}.",
            "Allow users to recover from interrupted {artifact}.",
        ],
    },
    "imports": {
        "artifacts": ["CSV customer imports", "inventory imports", "product catalog imports", "bulk contact imports", "order imports"],
        "tasks": [
            "Validate {artifact} before creating records.",
            "Prevent partial writes during failed {artifact}.",
            "Report row-level errors for {artifact}.",
            "Detect duplicate records during {artifact}.",
            "Allow users to preview changes before running {artifact}.",
            "Handle interrupted {artifact} without duplicating records.",
        ],
    },
    "exports": {
        "artifacts": ["invoice exports", "customer exports", "report exports", "audit exports", "order exports"],
        "tasks": [
            "Create downloadable files for {artifact}.",
            "Show export progress for long-running {artifact}.",
            "Prevent duplicate jobs for repeated {artifact}.",
            "Expire old files generated by {artifact}.",
            "Allow users to cancel pending {artifact}.",
            "Notify users when {artifact} fail.",
        ],
    },
    "inventory": {
        "artifacts": ["stock adjustments", "inventory transfers", "replenishment requests", "reserved stock", "SKU updates"],
        "tasks": [
            "Prevent negative inventory during {artifact}.",
            "Detect conflicts during concurrent {artifact}.",
            "Track history for {artifact}.",
            "Require validation before applying {artifact}.",
            "Allow rollback of incorrect {artifact}.",
            "Notify operators when {artifact} fail.",
        ],
    },
    "search": {
        "artifacts": ["product search", "customer search", "knowledge base search", "order search", "document search"],
        "tasks": [
            "Improve relevance for {artifact}.",
            "Add filters to {artifact}.",
            "Handle empty results in {artifact}.",
            "Prevent stale results in {artifact}.",
            "Support pagination for {artifact}.",
            "Track failed queries in {artifact}.",
        ],
    },
    "notifications": {
        "artifacts": ["email notifications", "SMS notifications", "push notifications", "digest emails", "delivery reminders"],
        "tasks": [
            "Prevent duplicate {artifact}.",
            "Allow users to manage preferences for {artifact}.",
            "Retry failed {artifact}.",
            "Stop sending {artifact} after cancellation.",
            "Show delivery status for {artifact}.",
            "Handle bounced {artifact}.",
        ],
    },
    "billing": {
        "artifacts": ["refund requests", "invoice generation", "subscription changes", "payment retries", "credit adjustments"],
        "tasks": [
            "Validate {artifact} before applying changes.",
            "Prevent duplicate {artifact}.",
            "Track history for {artifact}.",
            "Handle failed {artifact}.",
            "Show users the outcome of {artifact}.",
            "Prevent inconsistent totals during {artifact}.",
        ],
    },
    "scheduling": {
        "artifacts": ["appointment booking", "calendar availability", "reservation changes", "technician scheduling", "room booking"],
        "tasks": [
            "Prevent overlapping {artifact}.",
            "Handle cancellations for {artifact}.",
            "Show conflicts during {artifact}.",
            "Notify participants about {artifact}.",
            "Support rescheduling for {artifact}.",
            "Preserve history for {artifact}.",
        ],
    },
}

CONTEXTS = [
    "",
    " for mobile users",
    " during peak traffic",
    " when the previous attempt failed",
    " when multiple users act at the same time",
    " without losing existing records",
    " before confirming the action",
    " after a background job is interrupted",
]

def stable_id(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]

def main() -> None:
    random.seed(SEED)
    rows = []
    seen = set()

    for family, spec in FAMILIES.items():
        produced = 0
        attempts = 0
        while produced < TARGET_PER_FAMILY and attempts < TARGET_PER_FAMILY * 20:
            attempts += 1
            artifact = random.choice(spec["artifacts"])
            task = random.choice(spec["tasks"])
            context = random.choice(CONTEXTS)
            instruction = (task.format(artifact=artifact) + context).strip()
            instruction = instruction.replace("..", ".")
            key = instruction.lower()
            if key in seen:
                continue
            seen.add(key)
            rows.append({
                "instruction_id": stable_id(instruction),
                "family": family,
                "instruction": instruction,
                "source": "programmatic_family_v2",
            })
            produced += 1

    random.shuffle(rows)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")

    print("written", len(rows))
    print("out", OUT)

if __name__ == "__main__":
    main()
