from __future__ import annotations

import hashlib
import json
import random
from pathlib import Path

OUT = Path("training/datasets/product_agent/generated_instructions/instructions_v3_family_clean.jsonl")
TARGET_PER_FAMILY = 500
SEED = 43

FAMILIES = {
    "authentication": {
        "artifacts": ["login attempts", "password reset requests", "MFA challenges", "user sessions", "device trust prompts", "account recovery requests"],
        "tasks": [
            "Limit repeated {artifact}.",
            "Prevent duplicate {artifact}.",
            "Improve failure handling for {artifact}.",
            "Require clearer user feedback when {artifact} fail.",
            "Detect suspicious patterns in {artifact}.",
            "Allow users to recover from interrupted {artifact}.",
        ],
    },
    "imports": {
        "artifacts": ["CSV customer imports", "inventory imports", "product catalog imports", "bulk contact imports", "order imports"],
        "tasks": [
            "Validate {artifact} before creating records.",
            "Prevent partial writes during failed {artifact}.",
            "Report row-level errors for {artifact}.",
            "Detect duplicate records during {artifact}.",
            "Allow users to preview changes before running {artifact}.",
            "Handle interrupted {artifact} without duplicating records.",
        ],
    },
    "exports": {
        "artifacts": ["invoice exports", "customer exports", "report exports", "audit exports", "order exports"],
        "tasks": [
            "Create downloadable files for {artifact}.",
            "Show export progress for long-running {artifact}.",
            "Prevent duplicate jobs for repeated {artifact}.",
            "Expire old files generated by {artifact}.",
            "Allow users to cancel pending {artifact}.",
            "Notify users when {artifact} fail.",
        ],
    },
    "inventory": {
        "artifacts": ["stock adjustments", "inventory transfers", "replenishment requests", "reserved stock", "SKU updates"],
        "tasks": [
            "Prevent negative inventory during {artifact}.",
            "Detect conflicts during concurrent {artifact}.",
            "Track history for {artifact}.",
            "Require validation before applying {artifact}.",
            "Allow rollback of incorrect {artifact}.",
            "Notify operators when {artifact} fail.",
        ],
    },
    "search": {
        "artifacts": ["product search", "customer search", "knowledge base search", "order search", "document search"],
        "tasks": [
            "Improve relevance for {artifact}.",
            "Add filters to {artifact}.",
            "Handle empty results in {artifact}.",
            "Prevent stale results in {artifact}.",
            "Support pagination for {artifact}.",
            "Track failed queries in {artifact}.",
        ],
    },
    "notifications": {
        "artifacts": ["email notifications", "SMS notifications", "push notifications", "digest emails", "delivery reminders"],
        "tasks": [
            "Prevent duplicate {artifact}.",
            "Allow users to manage preferences for {artifact}.",
            "Retry failed {artifact}.",
            "Stop sending {artifact} after cancellation.",
            "Show delivery status for {artifact}.",
            "Handle bounced {artifact}.",
        ],
    },
    "billing": {
        "artifacts": ["refund requests", "invoice generation", "subscription changes", "payment retries", "credit adjustments"],
        "tasks": [
            "Validate {artifact} before applying changes.",
            "Prevent duplicate {artifact}.",
            "Track history for {artifact}.",
            "Handle failed {artifact}.",
            "Show users the outcome of {artifact}.",
            "Prevent inconsistent totals during {artifact}.",
        ],
    },
    "scheduling": {
        "artifacts": ["appointment booking", "calendar availability", "reservation changes", "technician scheduling", "room booking"],
        "tasks": [
            "Prevent overlapping {artifact}.",
            "Handle cancellations for {artifact}.",
            "Show conflicts during {artifact}.",
            "Notify participants about {artifact}.",
            "Support rescheduling for {artifact}.",
            "Preserve history for {artifact}.",
        ],
    },
}

CONTEXTS_BY_FAMILY = {
    "authentication": [
        "",
        "after several failed attempts",
        "when users switch devices",
        "when the recovery flow is interrupted",
        "for mobile users",
    ],
    "imports": [
        "",
        "before creating records",
        "when validation fails midway",
        "for large files",
        "without duplicating records",
    ],
    "exports": [
        "",
        "for long-running jobs",
        "when file generation fails",
        "without creating duplicate jobs",
        "for large reports",
    ],
    "inventory": [
        "",
        "during concurrent updates",
        "when stock counts change during processing",
        "while preserving adjustment history",
        "without creating negative stock",
    ],
    "search": [
        "",
        "for large result sets",
        "when filters change",
        "when the index is stale",
        "for mobile users",
    ],
    "notifications": [
        "",
        "when delivery fails",
        "after users change notification preferences",
        "when the related record is cancelled",
        "during high-volume sending",
    ],
    "billing": [
        "",
        "when payment processing fails",
        "while preserving financial history",
        "before applying account changes",
        "when totals change after recalculation",
    ],
    "scheduling": [
        "",
        "when availability changes",
        "during concurrent booking attempts",
        "after cancellations",
        "across time zones",
    ],
}

def stable_id(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]

def main() -> None:
    random.seed(SEED)
    rows = []
    seen = set()

    for family, spec in FAMILIES.items():
        produced = 0
        attempts = 0
        while produced < TARGET_PER_FAMILY and attempts < TARGET_PER_FAMILY * 20:
            attempts += 1
            artifact = random.choice(spec["artifacts"])
            task = random.choice(spec["tasks"])
            context = random.choice(CONTEXTS_BY_FAMILY[family])
            base = task.format(artifact=artifact).rstrip(".")
            instruction = f"{base} {context}.".strip() if context else f"{base}."
            instruction = " ".join(instruction.split())
            key = instruction.lower()
            if key in seen:
                continue
            seen.add(key)
            rows.append({
                "instruction_id": stable_id(instruction),
                "family": family,
                "instruction": instruction,
                "source": "programmatic_family_v3",
            })
            produced += 1

    random.shuffle(rows)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")

    print("written", len(rows))
    print("out", OUT)

if __name__ == "__main__":
    main()
