from __future__ import annotations

import socket
import subprocess
from pathlib import Path

import pytest

import agentic_network.project_test_generation_agent.runtime as test_generation_runtime
from agentic_network.project_patch_apply_agent.runtime import apply_project_patch
from agentic_network.project_test_generation_agent.run import main as generation_cli_main
from agentic_network.project_test_generation_agent.runtime import generate_project_tests
from agentic_network.project_test_runner_agent.runtime import run_project_verification


def _allow_temp(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("ANN_ALLOW_TEMP_PROJECT_TEST_GENERATION_TARGETS", "1")
    monkeypatch.setenv("ANN_ALLOW_TEMP_PROJECT_PATCH_TARGETS", "1")
    monkeypatch.setenv("ANN_ALLOW_TEMP_PROJECT_TEST_TARGETS", "1")
    monkeypatch.setenv("ANN_PROJECT_PATCH_TOKEN", "local-test-token")


def _project(tmp_path: Path) -> Path:
    root = tmp_path / "demo-project"
    root.mkdir()
    (root / "README.md").write_text(
        "# Demo Project\n\nPurpose: generated by ANN for local verification.\n",
        encoding="utf-8",
    )
    return root


def test_generates_67_plan_artifacts(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    _allow_temp(monkeypatch)
    root = _project(tmp_path)

    result = generate_project_tests(root, "outputs/runs/test-generation")

    assert result.status == "VALID"
    assert any(path.endswith("67_project_test_generation_plan.md") for path in result.artifacts)
    assert any(path.endswith("67_project_test_generation_plan.json") for path in result.artifacts)


def test_generates_68_patch_set_artifact(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    _allow_temp(monkeypatch)
    root = _project(tmp_path)

    result = generate_project_tests(root, "outputs/runs/test-generation")

    assert any(path.endswith("68_generated_test_patch_set.md") for path in result.artifacts)
    assert result.test_patch_files


def test_generates_non_trivial_python_test_patch(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    _allow_temp(monkeypatch)
    root = _project(tmp_path)

    result = generate_project_tests(root, "outputs/runs/test-generation")
    patch_text = Path(result.test_patch_files[0]).read_text(encoding="utf-8")

    assert "README.md" in patch_text
    assert "assert readme.is_file()" in patch_text
    assert "assert any(marker in text for marker in markers)" in patch_text


def test_rejects_trivial_assert_true_tests(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    _allow_temp(monkeypatch)
    root = _project(tmp_path)

    result = generate_project_tests(root, "outputs/runs/test-generation")
    patch_text = "\n".join(Path(path).read_text(encoding="utf-8") for path in result.test_patch_files)

    assert "assert True" not in patch_text
    assert "assert 1 == 1" not in patch_text
    assert result.validation_errors == []


def test_no_targets_returns_no_targets(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    _allow_temp(monkeypatch)
    root = tmp_path / "empty-project"
    root.mkdir()

    result = generate_project_tests(root, "outputs/runs/test-generation")

    assert result.status == "NO_TARGETS"
    assert result.test_patch_files == []


def test_blocks_ann_repo_as_project_root() -> None:
    result = generate_project_tests(test_generation_runtime.REPO_ROOT, "outputs/runs/test-generation")

    assert result.status == "BLOCKED"
    assert any("ANN repository" in error for error in result.validation_errors)


def test_repo_child_generated_project_test_generation_allowed(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    _allow_temp(monkeypatch)
    repo = tmp_path / "AgenticEngineeringNetwork"
    root = repo / "outputs" / "autonomous_capability_projects" / "crm" / "crm"
    root.mkdir(parents=True)
    (root / "README.md").write_text("# Demo\n\nPurpose: generated by ANN.\n", encoding="utf-8")
    monkeypatch.setattr(test_generation_runtime, "REPO_ROOT", repo.resolve())

    result = generate_project_tests(root, "outputs/runs/test-generation")

    assert result.status == "VALID"
    assert result.test_patch_files


def test_blocks_mnt_c() -> None:
    result = generate_project_tests("/mnt/c/ANNProjects/demo", "outputs/runs/test-generation")

    assert result.status == "BLOCKED"
    assert any("C: and /mnt/c" in error for error in result.validation_errors)


def test_blocks_c_drive() -> None:
    result = generate_project_tests("C:\\ANNProjects\\demo", "outputs/runs/test-generation")

    assert result.status == "BLOCKED"
    assert any("C: and /mnt/c" in error for error in result.validation_errors)


def test_blocks_git_path(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    _allow_temp(monkeypatch)
    root = tmp_path / ".git" / "demo"
    root.mkdir(parents=True)

    result = generate_project_tests(root, "outputs/runs/test-generation")

    assert result.status == "BLOCKED"
    assert any("Protected" in error for error in result.validation_errors)


def test_does_not_install_dependencies(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    _allow_temp(monkeypatch)
    root = _project(tmp_path)

    generate_project_tests(root, "outputs/runs/test-generation")

    assert not (root / "node_modules").exists()
    assert not (root / ".venv").exists()


def test_does_not_use_internet(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    _allow_temp(monkeypatch)
    root = _project(tmp_path)

    def fail_network(*_args: object, **_kwargs: object) -> None:
        raise AssertionError("Project Test Generation must not use internet.")

    monkeypatch.setattr(socket, "create_connection", fail_network)

    assert generate_project_tests(root, "outputs/runs/test-generation").status == "VALID"


def test_does_not_execute_terminal(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    _allow_temp(monkeypatch)
    root = _project(tmp_path)

    def fail_subprocess(*_args: object, **_kwargs: object) -> None:
        raise AssertionError("Project Test Generation must not execute terminal commands.")

    monkeypatch.setattr(subprocess, "run", fail_subprocess)

    assert generate_project_tests(root, "outputs/runs/test-generation").status == "VALID"


def test_generated_patch_requires_approval_to_apply(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    _allow_temp(monkeypatch)
    root = _project(tmp_path)
    generated = generate_project_tests(root, "outputs/runs/test-generation")

    dry = apply_project_patch(root, generated.test_patch_files[0], dry_run=True)
    blocked = apply_project_patch(root, generated.test_patch_files[0], dry_run=False)

    assert dry.status == "DRY_RUN"
    assert blocked.status == "BLOCKED"
    assert not (root / "tests" / "python" / "test_project_contract.py").exists()


def test_generated_patch_can_be_applied_and_verified(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    _allow_temp(monkeypatch)
    root = _project(tmp_path)
    generated = generate_project_tests(root, "outputs/runs/test-generation")

    applied = apply_project_patch(
        root,
        generated.test_patch_files[0],
        approval_token="local-test-token",
        confirm_apply=True,
        dry_run=False,
    )
    verified = run_project_verification(root, confirm_run=True)

    assert applied.status == "APPLIED"
    assert verified.status == "PASSED"
    assert verified.commands_executed


def test_cli_run_works(tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]) -> None:
    _allow_temp(monkeypatch)
    root = _project(tmp_path)

    exit_code = generation_cli_main(
        [
            "--project-root",
            str(root),
            "--run-dir",
            "outputs/runs/test-generation",
            "--max-tests",
            "2",
        ]
    )

    output = capsys.readouterr().out
    assert exit_code == 0
    assert '"status": "VALID"' in output
