from __future__ import annotations

import json
import socket
import subprocess
from pathlib import Path

import pytest

from agentic_network.project_patch_apply_agent.run import main as patch_apply_main
from agentic_network.project_patch_apply_agent.runtime import (
    apply_project_patch,
    rollback_project_patch,
)
import agentic_network.project_patch_apply_agent.runtime as patch_apply_runtime


def _project_root(tmp_path: Path) -> Path:
    root = tmp_path / "generated_project"
    (root / "apps" / "api" / "app").mkdir(parents=True)
    (root / "outputs" / "runs" / "20260621_120000" / "patches").mkdir(parents=True)
    (root / "apps" / "api" / "app" / "main.py").write_text('print("old")\n', encoding="utf-8")
    return root


def _patch_file(root: Path, *, relative: str = "docs/features/accounts.md", body: str = "Accounts") -> Path:
    patch = root / "outputs" / "runs" / "20260621_120000" / "patches" / "patch_001.diff"
    patch.write_text(
        "\n".join(
            [
                f"diff --git a/{relative} b/{relative}",
                "new file mode 100644",
                "index 0000000..1111111",
                "--- /dev/null",
                f"+++ b/{relative}",
                "@@ -0,0 +1,3 @@",
                f"+# {body}",
                "+",
                "+Generated by test.",
                "",
            ]
        ),
        encoding="utf-8",
    )
    return patch


def _existing_file_patch(root: Path) -> Path:
    patch = root / "outputs" / "runs" / "20260621_120000" / "patches" / "patch_existing.diff"
    patch.write_text(
        "\n".join(
            [
                "diff --git a/apps/api/app/main.py b/apps/api/app/main.py",
                "--- a/apps/api/app/main.py",
                "+++ b/apps/api/app/main.py",
                "@@ -1 +1 @@",
                '-print("old")',
                '+print("new")',
                "",
            ]
        ),
        encoding="utf-8",
    )
    return patch


def _allow_temp(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("ANN_ALLOW_TEMP_PROJECT_PATCH_TARGETS", "1")


def test_dry_run_no_modifies_files(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    _allow_temp(monkeypatch)
    root = _project_root(tmp_path)
    patch = _patch_file(root)

    result = apply_project_patch(root, patch, dry_run=True)

    assert result.status == "DRY_RUN"
    assert result.files_modified == []
    assert not (root / "docs" / "features" / "accounts.md").exists()


def test_apply_requires_token(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    _allow_temp(monkeypatch)
    root = _project_root(tmp_path)
    patch = _patch_file(root)

    result = apply_project_patch(root, patch, confirm_apply=True, dry_run=False)

    assert result.status == "BLOCKED"
    assert any("approval_token" in error for error in result.validation_errors)


def test_apply_requires_confirm_apply(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    _allow_temp(monkeypatch)
    monkeypatch.setenv("ANN_PROJECT_PATCH_TOKEN", "local-test-token")
    root = _project_root(tmp_path)
    patch = _patch_file(root)

    result = apply_project_patch(root, patch, "local-test-token", confirm_apply=False, dry_run=False)

    assert result.status == "BLOCKED"
    assert any("confirm_apply" in error for error in result.validation_errors)


def test_apply_creates_backups(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    _allow_temp(monkeypatch)
    monkeypatch.setenv("ANN_PROJECT_PATCH_TOKEN", "local-test-token")
    root = _project_root(tmp_path)
    patch = _existing_file_patch(root)

    result = apply_project_patch(root, patch, "local-test-token", True, True, False)

    assert result.status == "APPLIED"
    assert result.backups_created
    backup = Path(result.backups_created[0])
    assert (backup / "manifest.json").is_file()
    assert (backup / "patch_applied.diff").is_file()
    assert (backup / "original" / "apps" / "api" / "app" / "main.py").is_file()
    assert (backup / "new" / "apps" / "api" / "app" / "main.py").is_file()


def test_apply_modifies_only_project_root(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    _allow_temp(monkeypatch)
    monkeypatch.setenv("ANN_PROJECT_PATCH_TOKEN", "local-test-token")
    root = _project_root(tmp_path)
    patch = _patch_file(root)

    result = apply_project_patch(root, patch, "local-test-token", True, True, False)

    assert result.status == "APPLIED"
    assert all(Path(path).resolve().is_relative_to(root.resolve()) for path in result.files_modified)


def test_path_traversal_blocked(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    _allow_temp(monkeypatch)
    root = _project_root(tmp_path)
    patch = _patch_file(root, relative="../escape.md")

    result = apply_project_patch(root, patch, dry_run=True)

    assert result.status == "BLOCKED"
    assert any("blocked" in error.lower() for error in result.validation_errors)


def test_mnt_c_blocked_by_default(tmp_path: Path) -> None:
    result = apply_project_patch("/mnt/c/ANNProjects/crm", "patch.diff", dry_run=True)

    assert result.status == "BLOCKED"
    assert any("blocked" in error.lower() for error in result.validation_errors)


def test_c_drive_blocked_by_default(tmp_path: Path) -> None:
    result = apply_project_patch("C:\\ANNProjects\\crm", "patch.diff", dry_run=True)

    assert result.status == "BLOCKED"


def test_git_path_blocked(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    _allow_temp(monkeypatch)
    root = _project_root(tmp_path)
    patch = _patch_file(root, relative=".git/config")

    result = apply_project_patch(root, patch, dry_run=True)

    assert result.status == "BLOCKED"
    assert any(".git" in error for error in result.validation_errors)


def test_ann_repo_blocked() -> None:
    result = apply_project_patch(patch_apply_runtime.REPO_ROOT, "patch.diff", dry_run=True)

    assert result.status == "BLOCKED"
    assert any("ANN repository" in error for error in result.validation_errors)


def test_repo_child_generated_project_allowed(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    _allow_temp(monkeypatch)
    repo = tmp_path / "AgenticEngineeringNetwork"
    root = repo / "outputs" / "autonomous_capability_projects" / "crm" / "crm"
    (root / "outputs" / "runs" / "20260621_120000" / "patches").mkdir(parents=True)
    monkeypatch.setattr(patch_apply_runtime, "REPO_ROOT", repo.resolve())
    monkeypatch.setenv("ANN_PROJECT_PATCH_TOKEN", "local-test-token")
    patch = _patch_file(root)

    result = apply_project_patch(root, patch, "local-test-token", True, True, False)

    assert result.status == "APPLIED"
    assert (root / "docs" / "features" / "accounts.md").is_file()


def test_rollback_possible(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    _allow_temp(monkeypatch)
    monkeypatch.setenv("ANN_PROJECT_PATCH_TOKEN", "local-test-token")
    root = _project_root(tmp_path)
    patch = _existing_file_patch(root)

    result = apply_project_patch(root, patch, "local-test-token", True, True, False)
    rollback = rollback_project_patch(result.backups_created[0], confirm_rollback=True)

    assert rollback.status == "ROLLED_BACK"
    assert (root / "apps" / "api" / "app" / "main.py").read_text(encoding="utf-8") == 'print("old")\n'


def test_consensus_updated(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    _allow_temp(monkeypatch)
    monkeypatch.setenv("ANN_PROJECT_PATCH_TOKEN", "local-test-token")
    root = _project_root(tmp_path)
    patch = _patch_file(root)

    result = apply_project_patch(root, patch, "local-test-token", True, True, False)

    assert result.consensus["patch_apply"] is True
    assert list((root / "outputs" / "runs").glob("*_patch_apply/38_consensus_decision.json"))


def test_action_plan_updated(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    _allow_temp(monkeypatch)
    monkeypatch.setenv("ANN_PROJECT_PATCH_TOKEN", "local-test-token")
    root = _project_root(tmp_path)
    patch = _patch_file(root)

    result = apply_project_patch(root, patch, "local-test-token", True, True, False)

    assert result.next_action == "review_and_run_project_tests"
    assert list((root / "outputs" / "runs").glob("*_patch_apply/39_action_plan.json"))


def test_self_healing_can_activate(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    _allow_temp(monkeypatch)
    root = _project_root(tmp_path)
    patch = _patch_file(root, relative="models/bad.md")

    result = apply_project_patch(root, patch, dry_run=False, confirm_apply=True)

    assert result.self_healing_triggered is True


def test_retry_patch_can_generate(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    _allow_temp(monkeypatch)
    root = _project_root(tmp_path)
    patch = _patch_file(root, relative="models/bad.md")

    result = apply_project_patch(root, patch, dry_run=False, confirm_apply=True)

    assert result.retry_patch_generated is not None
    assert Path(result.retry_patch_generated).is_file()


def test_no_modifies_ann(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    readme = patch_apply_runtime.REPO_ROOT / "README.md"
    before = readme.read_text(encoding="utf-8")

    test_ann_repo_blocked()

    assert readme.read_text(encoding="utf-8") == before


def test_no_installs_dependencies(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    _allow_temp(monkeypatch)
    monkeypatch.setenv("ANN_PROJECT_PATCH_TOKEN", "local-test-token")
    root = _project_root(tmp_path)
    patch = _patch_file(root)

    apply_project_patch(root, patch, "local-test-token", True, True, False)

    assert not (root / "node_modules").exists()
    assert not (root / ".venv").exists()


def test_no_internet(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    _allow_temp(monkeypatch)

    def fail_network(*_args: object, **_kwargs: object) -> None:
        raise AssertionError("Project Patch Apply must not use internet.")

    monkeypatch.setattr(socket, "create_connection", fail_network)
    root = _project_root(tmp_path)
    patch = _patch_file(root)

    assert apply_project_patch(root, patch, dry_run=True).status == "DRY_RUN"


def test_no_free_terminal_execution(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    _allow_temp(monkeypatch)

    def fail_subprocess(*_args: object, **_kwargs: object) -> None:
        raise AssertionError("Project Patch Apply must not execute terminal commands.")

    monkeypatch.setattr(subprocess, "run", fail_subprocess)
    root = _project_root(tmp_path)
    patch = _patch_file(root)

    assert apply_project_patch(root, patch, dry_run=True).status == "DRY_RUN"


def test_cli_dry_run_works(tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]) -> None:
    _allow_temp(monkeypatch)
    root = _project_root(tmp_path)
    patch = _patch_file(root)

    exit_code = patch_apply_main(["--project-root", str(root), "--patch", str(patch), "--dry-run"])

    payload = json.loads(capsys.readouterr().out)
    assert exit_code == 0
    assert payload["status"] == "DRY_RUN"
